name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository Contents
        uses: actions/checkout@v4

      - name: Remove Git Folders and Files Before Upload
        run: rm -rf .git .github .gitignore .gitattributes

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sync Repository Contents to Azure Blob Storage
        run: |
          az storage blob sync \
            --account-name ${{ secrets.AZURE_BLOB_ACCOUNT_NAME }} \
            --container ${{ secrets.AZURE_BLOB_CONTAINER_NAME }} \
            --source . \
            --delete-destination true \
            --only-show-errors
