name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ./
          container_name: mc-launcher-api
          connection_string: ${{ secrets.ConnectionString }}
          overwrite: 'true'