name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Contents
        uses: actions/checkout@v2
        with:
            lfs: 'true'
      - name: Pull GitHub LFS Files
        run: git lfs pull
      - name: Remove Git Folders and Files Before Upload
        run: rm -rf .git .github .gitignore .gitattributes
      - name: Upload Repository Contents to Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ./
          container_name: mc-launcher-api
          connection_string: ${{ secrets.ConnectionString }}
          sync: 'true'