name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Contents
        uses: actions/checkout@v4

      - name: Remove Git Folders and Files Before Upload
        run: rm -rf .git .github .gitignore .gitattributes

      - name: Install Azure CLI
        run: |
          if ! command -v az &> /dev/null; then
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi

      - name: Sync Repository Contents to Azure Blob Storage
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.ConnectionString }}
        run: |
          az storage blob sync \
            --connection-string "$AZURE_STORAGE_CONNECTION_STRING" \
            --container mc-launcher-api \
            --source . \
            --delete-destination true \
            --only-show-errors
