
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = 777181789382115328
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 16

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Initializing"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "mclogo"
	#The text that gets displayed when the small image is hovered
	smallImageText = "-- (-- Players Online)"
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Main Menu"
	#The seconds line of text under the app name
	state = "Choosing a Mode"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (-- Players Online)"
	#The buttons to display on Discord
	#buttons = []
      [[main_menu.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Main Menu"
	#The second line of text under the app name
	state = "Looking for a Server"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (-- Players Online)"
	#The buttons to display on Discord
	#buttons = []
      [[server_list.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "Main Menu"
	#The second line of text under the app name
	state = "Looking for a Realm"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (-- Players Online)"
	#The buttons to display on Discord
	#buttons = []
      [[realms_list.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "In Game"
	#The second line of text under the app name
	state = "Joining Game..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (-- Players Online)"
	#The buttons to display on Discord
	#buttons = []
      [[join_game.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "In Game"
	#The second line of text under the app name
	state = "Playing Singleplayer World (%world%)"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (1 Player Online)"
	#The buttons to display on Discord
	#buttons = []
      [[single_player.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "In Game"
	#The second line of text under the app name
	state = "Day %day%, %weather%"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "%motd%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (%players%/%maxplayers% Players Online)"
	#The buttons to display on Discord
	#buttons = []
      [[multi_player.buttons]]
      	label = "Join"
            url = "https://minecraft.micatechnologies.com/alto.html"

      [[multi_player.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "In Game"
	#The second line of text under the app name
	state = "Playing on a Realm (%realmname%)"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (%players%/%maxplayers% Players Online)"
	#The buttons to display on Discord
	#buttons = []
      [[realms.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo512"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Based on Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "%playerhead%"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%player% (-- Players Online)"
	#The buttons to display on Discord
	#buttons = []
      [[generic.buttons]]
      	label = "Online Map"
            url = "https://minecraft.micatechnologies.com/alto-map.html"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"
		#The first line of text under the app name
		description = "%player% is in The Overworld"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = "overworld"
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Overworld"
		#The Asset ID of the image to display as the small image
		smallImageKey = "mclogo"
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"
		#The first line of text under the app name
		description = "%player% is in The Nether"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = "nether"
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Nether"
		#The Asset ID of the image to display as the small image
		smallImageKey = "mclogo"
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"
		#The first line of text under the app name
		description = "%player% is in The End"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = "end"
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the End"
		#The Asset ID of the image to display as the small image
		smallImageKey = "mclogo"
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []

